version: "3.0"
services:
  db:
    container_name: "db"
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    networks:
      - custom
    volumes:
      - db-data:/var/lib/postgresql/data
  video_hosting_app:
    container_name: video_hosting_app
    image: video_hosting_app # Specify the name of the Docker image to be built
    depends_on:
      - db
      - alembic_migrations
    environment:
      DB_URL: "postgresql+asyncpg://postgres:postgres@db:5432/postgres"
      SENTRY_URL: "https://5a3fb01ba8837fb4b77b347f6df306b7@o4505846124642304.ingest.sentry.io/4505846223732736"
      PORT: "8000"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - custom
  alembic_migrations:
    container_name: alembic_migrations
    image: alembic_migrations # Specify the name of the Docker image to be built
    command: ./run.sh
    depends_on:
      - db
    environment:
      ALEMBIC_DATABASE_URL: "postgresql://postgres:postgres@db/postgres"
      DB_URL: "postgresql+asyncpg://postgres:postgres@db:5432/postgres"
      SENTRY_URL: "https://5a3fb01ba8837fb4b77b347f6df306b7@o4505846124642304.ingest.sentry.io/4505846223732736"
      PORT: "8001"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    networks:
      - custom
  prometheus:
    depends_on:
      - video_hosting_app
    image: prom/prometheus:v2.43.0
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    networks:
      - custom
  grafana:
    image: grafana/grafana:8.5.22
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - grafana-config:/etc/grafana
    depends_on:
      - prometheus
    restart: always
    networks:
      - custom
    user: "0"
networks:
  custom:
    driver: bridge
volumes:
  db-data:
  grafana-data:
  grafana-config:
  prometheus-data:
